name = "tph-api"
main = "src/index.js"
compatibility_date = "2023-03-03"
usage_model = "bundled"
env = { }
kv_namespaces = [
  { binding = "kv", id = "11bded6f459c4e4a8a83cb842e282b3e" }
]

[triggers]
crons = [ ]

[vars]